/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KeyRequest.java
 *
 * 
 */



import java.rmi.Naming;
import javax.swing.JOptionPane;

/**
 *
 *
 */
public class KeyRequest extends javax.swing.JFrame {

    /** Creates new form KeyRequest */

    String nod,xCord,yCord,passwd;
    public KeyRequest() {
        initComponents();
		setSize(400,300);
		setVisible(true);
		this.setTitle("key Request");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
		jButton3= new javax.swing.JButton();

		jTxtArea=new javax.swing.JTextArea();
		jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setText("Node Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 60, 55, 14);

        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 100, 60, 14);
        jPanel1.add(jTextField1);
        jTextField2.setBounds(180, 100, 80, 20);
        jPanel1.add(jTextField2);
        jTextField1.setBounds(180, 60, 80, 20);

		jTxtArea.setColumns(20);
        jTxtArea.setRows(5);
        jScrollPane1.setViewportView(jTxtArea);
		jPanel1.add(jScrollPane1);
		jScrollPane1.setBounds(70, 220, 240, 110);

        jButton1.setText("Key Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 170, 93, 23);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 170, 80, 23);

		jButton3.setText("Communicate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(250, 170, 93, 23);
		//jPanel1.add(jTxtArea);
		//jTxtArea.setBounds(50, 200, 250, 70);
		jPanel1.add(jScrollPane1);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 30, 338, 448);

        pack();
		this.setTitle("Key Request");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(Main.nod);
         jTextField2.setText(Main.passwd);
    }//GEN-LAST:event_jButton2ActionPerformed

	

	 private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
		this.dispose();
        new Node();
    }

	

	

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("\njButton1_actionPerformed from Key request called.");
		// TODO: Add any handling code here
		String url="";
		String node=jTextField1.getText().trim();
        String ID=jTextField2.getText().trim();

                 if(!(node.equalsIgnoreCase(Main.nod) && ID.equalsIgnoreCase(Main.passwd)))
                {
                       JOptionPane.showMessageDialog(null,"Invalid user credentials");
                       jTextField1.setText("");
                       jTextField2.setText("");
                }
				else
				{
					try
					{
						System.out.println(node);
						System.out.println(ID);
						
						url="rmi://127.0.0.1/ecobj";
						System.out.println("-----Request Key Called------");
						ECInterface ecIntf=(ECInterface) Naming.lookup(url);
						int i=ecIntf.requestKey(node,ID,"89","80");
						
					}
					catch (Exception ex)
					{
						ex.printStackTrace();
					}
				}

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
	static javax.swing.JTextArea jTxtArea;

    private javax.swing.JScrollPane jScrollPane1;

    // End of variables declaration//GEN-END:variables

}
