/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Mst.java
 *
 * Created on Jan 26, 2010, 4:26:48 PM
 */


import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.SocketAddress;
import java.rmi.Naming;
import javax.swing.JOptionPane;

/**
 *
 * @author spiro13
 */
public class Mst extends javax.swing.JFrame {

    /** Creates new form Mst */
    //String nod,xCord,yCord,passwd;
    private String address;
    public Mst() {
        initComponents();
        setSize(450, 500);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKeys = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel1.setText("Node Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 40, 90, 14);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 70, 90, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel3.setText("X-Coordinate");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 100, 90, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel4.setText("Y-Coordinate");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 130, 90, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 40, 100, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(180, 70, 100, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(180, 100, 100, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(180, 130, 100, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jButton1.setText("Get Coordinates");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 180, 120, 23);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jButton2.setText("Construct MST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 180, 120, 23);

        txtKeys.setColumns(20);
        txtKeys.setRows(5);
        jScrollPane1.setViewportView(txtKeys);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 220, 240, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 50, 390, 350);

        pack();
		this.setTitle("MST Request");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         jTextField3.setText(Main.xCord);
		 jTextField2.setText(Main.passwd);
		 jTextField1.setText(Main.nod);
         jTextField4.setText(Main.yCord);
		 System.out.println(Main.xCord);
		 System.out.println(Main.yCord);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("\njButton2_actionPerformed(ActionEvent e) called.");
		String url="";
		String node=jTextField1.getText().trim();
        String ID=jTextField2.getText().trim();
        if(!(node.equalsIgnoreCase(Main.nod) && ID.equalsIgnoreCase(Main.passwd)))
        {
				System.out.println("Invalid user credentials");
                JOptionPane.showMessageDialog(null,"Invalid user credentials");
                jTextField1.setText("");
                jTextField2.setText("");
        }
		else
		{
        try
		{
			System.out.println(node);
			System.out.println(ID);

			url="rmi://127.0.0.1/ecobj";
			ECInterface ecIntf=(ECInterface) Naming.lookup(url);
			String s[]=ecIntf.requestMST(node,ID,Main.xCord,Main.yCord);
                        if(s[0].equalsIgnoreCase("false"))
                            JOptionPane.showMessageDialog(null,"Wait until all L sensors registered ");
                        else
                        {
                            //////////////// Show neighbouring nodes
                            String str="Neighbouring nodes are";
							String ss="a";
                            int i=1;
                            while(ss!=null)
                            {
								
                                str+="\n"+s[i];
                                new DBClass().insertRow("Neigh",s[i++],"","");
								ss=s[i];
                            }
							txtKeys.append(str);
                            JOptionPane.showMessageDialog(null,str);
							this.dispose();
							new KeyRequest();
                           // new DBClass().insertRow("Neigh",nod,pub,pri);
                            String myName="";

                                    //SocketAddress sockaddr=new InetSocketAddress(4555);
            //			InetAddress addr = InetAddress.getLocalHost();
            //			SocketAddress sockaddr = new InetSocketAddress(addr, 4565);
                                   // Socket clientSocket = new Socket();
                                   // clientSocket.connect(sockaddr);
                                   // String name ="";
                                   // DataOutputStream out1=new DataOutputStream(clientSocket.getOutputStream());
                                   // out1.writeUTF(myName);
                                   // System.out.println("After Writing");
                                   // DataInputStream opsa=new DataInputStream(clientSocket.getInputStream());
                                   // while(true)
                                    {
                                    //    String da=opsa.readUTF();
                                    //    System.out.println("Message from Server : "+ da);
                                     //   txtKeys.append(da);
                                      //  if(da.equals("release"))
                                        {
                                       //     break;
                                        }
                                    }
                        }
		}
		catch (Exception ex)
		{
			ex.printStackTrace();
		}
		}



    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextArea txtKeys;
    // End of variables declaration//GEN-END:variables

}
